fix: update AuthorizableUser interface
getjerry/nest-casl pull request #222
Opened 2021-12-30 02:53 UTC by mashirozx

fix: #221

2021-12-30 04:35 UTC, liquidautumn approved these changes

2021-12-30 05:44 UTC, mashirozx commented
Oh no,  I have no idea about this type chain 😢

2022-01-01 11:52 UTC, nguyenthenguyen commented on src/interfaces/authorizable-user.interface.ts
> +export interface AuthorizableUser<Roles = string, Id = string | number> {
@mashirozx @liquidautumn Can we change `Id` to `any` type?

```
export interface AuthorizableUser<Roles = string, Id = any> {
  id: Id;
  roles: Array<Roles>;
}

```

2022-01-14 03:06 UTC, liquidautumn requested changes
Research required

2022-06-28 06:24 UTC, ppodds commented
The problem is still there. Has any turnaround?

2022-08-10 08:33 UTC, rubiin commented
@liquidautumn any updates on this. Seems to be a blocking issue for nosql dbs where the id is mostly string

2022-12-01 23:57 UTC, liquidautumn commented
Bug fixed in #534

2022-12-01 23:57 UTC, closed without merging